server:
  port: 8080
---
kafka:
  bootstrapServers: localhost:9092

---

spring:
  profiles: default
#  kafka:
#    consumer:
#      bootstrap-servers: localhost:9092
#      group-id: customer
#      auto-offset-reset: earliest
#      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#    producer:
#      bootstrap-servers: localhost:9092
#      key-serializer: org.apache.kafka.common.serialization.StringSerializer
#      value-serializer: org.apache.kafka.common.serialization.StringSerializer
  jpa:
#    properties:
#      hibernate:
#        show_sql: true
#        format_sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQL57Dialect
  datasource:
    url: jdbc:mysql://database-1.csvj9ae9rzmk.ap-northeast-2.rds.amazonaws.com:3306/ezins
    username: sklina
    password: 123456
    driverClassName: org.mariadb.jdbc.Driver
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
#          brokers: 54.180.71.26:9092
        streams:
          binder:
            configuration:
              default:
                key:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
                value:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
      bindings:
        event-in:
          group: customer
          destination: ezinsurance
          contentType: application/json
        event-out:
          destination: ezinsurance
          contentType: application/json

logging:
  level:
    org.hibernate.type: trace
    org.springframework.cloud: debug
server:
  port: 8082
---

mybatis:
  mapper-locations: /mapper/*.xml

